Prevent pod scaling if app is the target of an HPA
theketchio/ketch pull request #201
Opened 2021-11-29 21:17 UTC by DavisFrench

# Description

If there is an HPA for an app, we do not want units to be scaled in canary deployment

Fixes # 2147

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (documentation addition or typo, file relocation)

## Testing

- [ ] New tests were added with this PR that prove my fix is effective or that my feature works (describe below this bullet)
- [ ] This change requires no testing (i.e. documentation update)

## Documentation

- [x] All added public packages, funcs, and types have been documented with doc comments
- [x] I have commented my code, particularly in hard-to-understand areas

## Final Checklist:

- [x] I followed standard [GitHub flow](https://guides.github.com/introduction/flow/) guidelines
- [x] I have performed a self-review of my own code
- [ ] My changes generate no new warnings

## Additional Information (omit if empty)

Please include anything else relevant to this PR that may be useful to know.

2021-11-30 14:53 UTC, aleksej-paschenko requested changes

2021-11-30 14:56 UTC, DavisFrench commented on internal/controllers/app_controller.go
> +	var deploymentNames []string
A map for the deployment names? I think that would work well.

2021-11-30 14:58 UTC, DavisFrench commented on internal/controllers/app_controller.go
> +		if err := r.List(ctx, &hpaList); err != nil {
I wanted to do that, but app.Spec.Framework does not have the shipa prefix and trying to use the namespace in the metadata of the app resulted in an empty string. I feel like adding in the "shipa" string manually might not be the most appropriate idea.

2021-11-30 18:14 UTC, DavisFrench commented on internal/controllers/app_controller.go
> +		if err := r.List(ctx, &hpaList); err != nil {
Switched to using `targetNamespace` like you suggested.

2021-11-30 19:19 UTC, DavisFrench commented on internal/controllers/app_controller.go
> +	var deploymentNames []string
I changed to a map, and also have the function return a map so that we can disable scaling per process.

2021-11-30 19:23 UTC, DavisFrench commented on internal/api/v1beta1/app_types.go
> +		if app.Spec.Canary.Target != nil && !disableScale {
I have implemented a version that will allow for disabling scaling per process. I was having some trouble thinking of a clean way of also being able to limit based on Version.

Something like using a map where the key is the process appended with the deployment version I think would work, but would need some string parsing in the doCanary function. Do we want to have that level of control or leave it at the process level?

2021-12-01 14:04 UTC, DavisFrench commented on internal/controllers/app_controller.go
> +			if target.Spec.ScaleTargetRef.Name == deploymentName {
You mean the kind and the apiVersion of the scaleTargetRef matches the kinds of the deployment?

2021-12-01 15:03 UTC, DavisFrench commented on internal/controllers/app_controller.go
> +			if target.Spec.ScaleTargetRef.Name == deploymentName {
I added a check to ensure that the apiVersion and kind of the HPA's target are what is expected.

2021-12-01 15:06 UTC, aleksej-paschenko approved these changes
looks great!

2021-12-01 16:30 UTC, stinkyfingers approved these changes

2021-12-01 18:00 UTC, merged